FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY chatbot_app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY chatbot_app ./chatbot_app

EXPOSE 8001

CMD ["uvicorn", "chatbot_app.main:app", "--host", "0.0.0.0", "--port", "8001"]
